[pyprland]
plugins = ["scratchpads", "wallpapers"]

[scratchpads.spotify]
animation = "fromTop"
command = 'spotify'
class = "Spotify"
size = "90% 90%"
position = "5% 5%"

[scratchpads.thunderbird]
animation = "fromTop"
command = 'thunderbird'
class = "thunderbird"
size = "90% 90%"
position = "5% 5%"

[scratchpads.install]
animation = "fromTop"
command = 'kitty --class="kitty-install" "$HOME/.config/hypr/install.sh"'
class = "kitty-install"
size = "70% 70%"
position = "15% 15%"
lazy = true

[scratchpads.update]
animation = "fromTop"
command = 'kitty --class="kitty-update" "$HOME/.config/hypr/update.sh"'
class = "kitty-update"
size = "70% 70%"
position = "15% 15%"
lazy = true

[scratchpads.btop]
animation = "fromTop"
command = 'kitty --class="kitty-btop" "btop"'
class = "kitty-btop"
size = "70% 70%"
position = "15% 15%"

[wallpapers]
path = "~/.config/hypr/wallpapers/"
extensions = ["png", "jpg", "jpeg", "webp", "JPG"]
interval = 10
recurse = true
command = 'swww img --transition-type any "[file]"'
clear_command = "swww clear"
