[pyprland]
plugins = ["scratchpads", "wallpapers"]

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "Spotify"
size = "80% 80%"
position = "10% 10%"
unfocus = "hide"

[scratchpads.webcord]
animation = "fromTop"
command = "webcord"
class = "WebCord"
size = "90% 90%"
position = "5% 5%"
unfocus = "hide"

[scratchpads.thunar]
animation = "fromTop"
command = "thunar"
class = "thunar"
size = "60% 80%"
position = "20% 10%"
unfocus = "hide"

[scratchpads.betterbird]
animation = "fromTop"
command = "betterbird"
class = "betterbird"
size = "90% 90%"
position = "5% 5%"
unfocus = "hide"

[scratchpads.volume]
animation = "fromTop"
command = "pulsecontrol"
class = "org.test.pulsecontrol"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"

[scratchpads.install]
animation = "fromTop"
command = 'kitty --class="kitty-install" "$HOME/.config/install.sh"'
class = "kitty-install"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"
lazy = true

[scratchpads.update]
animation = "fromTop"
command = 'kitty --class="kitty-update" "$HOME/.config/update.sh"'
class = "kitty-update"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"
lazy = true

[scratchpads.btop]
animation = "fromTop"
command = "kitty --class='kitty-btop' 'btop'"
class = "kitty-btop"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"

[scratchpads.cava]
animation = "fromTop"
command = "kitty --class='kitty-cava' 'cava'"
class = "kitty-cava"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class='kitty-yazi' 'yazi'"
class = "kitty-yazi"
size = "70% 70%"
position = "15% 15%"
unfocus = "hide"

[wallpapers]
path = "~/.config/hypr/wallpapers/"
extensions = ["png", "jpg", "jpeg", "webp", "JPG"]
interval = 10
recurse = true
command = 'swww img --transition-type any "[file]"'
clear_command = "swww clear"
