[pyprland]
plugins = ["scratchpads"]

[scratchpads.thunderbird]
animation = "fromTop"
command = 'thunderbird'
class = "thunderbird"
size = "90% 90%"
position = "5% 5%"

[scratchpads.install]
animation = "fromTop"
command = 'kitty --class="kitty-install" "$HOME/.config/hypr/install.sh"'
class = "kitty-install"
size = "70% 70%"
position = "15% 15%"
lazy = true

[scratchpads.update]
animation = "fromTop"
command = 'kitty --class="kitty-update" "$HOME/.config/hypr/update.sh"'
class = "kitty-update"
size = "70% 70%"
position = "15% 15%"
lazy = true

[scratchpads.htop]
animation = "fromTop"
command = 'kitty --class="kitty-htop" "htop"'
class = "kitty-htop"
size = "70% 70%"
position = "15% 15%"
