"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'os'
style = 'diamond'
foreground = 'black'
background = 'blue'
leading_diamond = '╭─'
template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

[blocks.segments.properties]
linux = ''
macos = ''
windows = ''

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
foreground = 'black'
background = 'cyan'
template = ' {{ .Path }} '

[blocks.segments.properties]
folder_icon = ''
home_icon = ''
style = 'mixed'
mixed_threshold = 15

[[blocks.segments]]
type = 'git'
style = 'accordion'
powerline_symbol = ''
foreground = 'black'
background = 'yellow'
background_templates = [
    '{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}',
    '{{ if and (gt .Ahead 0) (gt .Behind 0) }}green{{ end }}',
    '{{ if gt .Ahead 0 }}red{{ end }}',
    '{{ if gt .Behind 0 }}red{{ end }}',
]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '

[blocks.segments.properties]
branch_icon = ' '
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = 'text'
style = 'accordion'
powerline_symbol = ''
foreground = 'black'
background = 'green'
template = '{{if .Env.ZELLIJ_SESSION_NAME}}  $ZELLIJ_SESSION_NAME {{end}}'

[[blocks.segments]]
type = 'executiontime'
style = 'diamond'
foreground = 'black'
background = 'magenta'
trailing_diamond = ''
template = '  {{ .FormattedMs }}⠀'

[blocks.segments.properties]
style = 'round'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'node'
style = 'diamond'
foreground = '#3C873A'
background = '#303030'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = ' <#cc3a3a></> '
yarn_icon = ' <#348cba></>'

[[blocks.segments]]
type = 'python'
style = 'diamond'
foreground = '#FFE873'
background = '#306998'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'java'
style = 'diamond'
foreground = '#ffffff'
background = '#0e8ac8'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'dotnet'
style = 'diamond'
foreground = '#0d6da8'
background = '#0e0e0e'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'go'
style = 'diamond'
foreground = '#06aad5'
background = '#ffffff'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'rust'
style = 'diamond'
foreground = '#925837'
background = '#f3f0ec'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'dart'
style = 'diamond'
foreground = '#055b9c'
background = '#e1e8e9'
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'angular'
style = 'diamond'
foreground = '#ce092f'
background = '#ffffff'
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'nx'
style = 'diamond'
foreground = '#ffffff'
background = '#1e293b'
leading_diamond = ' '
trailing_diamond = ' '
template = '{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'julia'
style = 'diamond'
foreground = '#359a25'
background = '#945bb3'
leading_diamond = ' '
trailing_diamond = ' '
template = '<#ca3c34></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'ruby'
style = 'diamond'
foreground = '#9c1006'
background = '#ffffff'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'azfunc'
style = 'diamond'
foreground = '#5398c2'
background = '#ffffff'
leading_diamond = ''
trailing_diamond = ' '
template = '<#f5bf45></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

[[blocks.segments]]
type = 'aws'
style = 'diamond'
foreground = '#faa029'
background = '#565656'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'

[[blocks.segments]]
type = 'kubectl'
style = 'diamond'
foreground = '#ffffff'
background = '#316ce4'
leading_diamond = ''
trailing_diamond = ''
template = ' {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'green'
template = '╰─'

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground = 'green'
foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
template = ''

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
foreground = "green"
foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
background = "transparent"
template = ' '
newline = true
