version = 2
final_space = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'root'
style = 'plain'
template = ' ⚡'
background = 'black'
foreground = 'red'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ""
template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
background = 'black'
foreground = 'white'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
alpine = ''
arch = ''
centos = ''
debian = ''
elementary = ''
fedora = ''
gentoo = ''
linux = ''
macos = ''
manjaro = ''
mint = ''
opensuse = ''
raspbian = ''
ubuntu = ''
windows = ''
wsl = ''

[[blocks.segments]]
type = 'path'
style = 'plain'
template = ' {{ .Path }} '
background = 'black'
foreground = 'blue'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
folder_icon = ''
folder_separator_icon = ' <darkGray> </>'
home_icon = ''
style = 'mixed'
mixed_threshold = 15

[[blocks.segments]]
type = 'git'
style = 'plain'
template = '<darkGray> </>{{ .HEAD }}{{ if .Staging.Changed }}<cyan>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
background = 'black'
foreground = 'green'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true

[[blocks.segments]]
type = 'executiontime'
style = 'diamond'
trailing_diamond = ''
template = '<darkGray> </>{{ .FormattedMs }}s '
background = 'black'
foreground = 'white'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
style = 'dallas'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ' '
template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}<transparent> / </>{{ .HostName }}'
background = 'black'
foreground = 'blue'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'time'
style = 'diamond'
trailing_diamond = ' '
template = '<darkGray>  </>{{ .CurrentDate | date .Format }} '
background = 'black'
foreground = 'blue'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
time_format = '3:04:05 PM'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
template = ''
background = ''
foreground = 'green'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
foreground = "green"
foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
background = "transparent"
template = ' '
newline = true
