# ▄▄▄▄▄▄                                  ▄▄▄▄                                ▄▄
# ██▀▀▀▀█▄                                ▀▀██                                ██
# ██    ██  ▀██  ███  ██▄███▄    ██▄████    ██       ▄█████▄  ██▄████▄   ▄███▄██
# ██████▀    ██▄ ██   ██▀  ▀██   ██▀        ██       ▀ ▄▄▄██  ██▀   ██  ██▀  ▀██
# ██          ████▀   ██    ██   ██         ██      ▄██▀▀▀██  ██    ██  ██    ██
# ██           ███    ███▄▄██▀   ██         ██▄▄▄   ██▄▄▄███  ██    ██  ▀██▄▄███
# ▀▀           ██     ██ ▀▀▀     ▀▀          ▀▀▀▀    ▀▀▀▀ ▀▀  ▀▀    ▀▀    ▀▀▀ ▀▀
#            ███      ██

[pyprland]
plugins = ["scratchpads", "wallpapers"]

[scratchpads.update]
animation = "fromTop"
command = 'kitty --class="kitty-update" "$HOME/.local/bin/update.sh"'
class = "kitty-update"
size = "70% 70%"
position = "15% 15%"
lazy = true

[scratchpads.thunderbird]
animation = "fromTop"
command = 'thunderbird'
class = "thunderbird"

[wallpapers]
interval = 15
extensions = ["png", "jpg", "jpeg", "webp", "JPG"]
path = '~/Pictures/wallpapers/'
recurse = true
command = '~/.local/bin/change-wallpaper.sh "[file]"'
clear_command = 'swww clear'
